package model

import (
	"strings"
	"time"

	"github.com/texttheater/golang-levenshtein/levenshtein"
)

var meniny map[string]Date

func addMeniny(names string, day int, month int) {
	z := strings.Split(names, ",")
	for _, n := range z {
		n = strings.TrimSpace(n)
		if n != "" {
			if meniny[n].Day > 0 { //duplicity
				continue
			}
			meniny[n] = Date{Day: day, Month: time.Month(month)}
		}
	}
}

func Meniny(name string) Date {
	if date, ok := meniny[name]; ok {
		return date
	}
	best := 1000
	bestN := ""
	options := levenshtein.DefaultOptions
	options.SubCost = 1
	nameR := []rune(name)
	for n := range meniny {
		l := levenshtein.DistanceForStrings([]rune(n), nameR, options)
		if l < best {
			best = l
			bestN = n
		}
	}
	return meniny[bestN]
}

func init() {
	meniny = make(map[string]Date, 0)
	// Januar
	addMeniny("Alexandra, Karina, Ábel, Makar, Karin, Kara, Sandra, Saša", 2, 1)
	addMeniny("Daniela, Danila, Danuta, Genovéva, Radmila", 3, 1)
	addMeniny("Drahoslav, Drahoľub, Drahomil, Drahoň, Drahoš, Duchoslav, León, Títus, Drahoľuba, Drahomila, Duchoslava, Leóna, Leónia", 4, 1)
	addMeniny("Andrea, Artúr", 5, 1)
	addMeniny("Antónia, Melchior, Melichar, Menhard", 6, 1)
	addMeniny("Bohuslava, Attila, Lucián, Bohuna, Boleslava, Božislava, Luciána", 7, 1)
	addMeniny("Severín, Čestmír, Pravomil, Čestmíra, Pravomila, Severína", 8, 1)
	addMeniny("Alexej, Alex, Domoľub, Julián, Pravoľub, Vladan, Vladen, Alexia, Pravoľuba, Vladana, Vladena", 9, 1)
	addMeniny("Dáša, Agatón, Dalimil, Dalimír, Dalimila, Dalimíra", 10, 1)
	addMeniny("Malvína, Honorát, Tasilo, Honoráta", 11, 1)
	addMeniny("Ernest, Arkád, Arnošt, Arkádia, Arnoštka, Erna, Ernestína", 12, 1)
	addMeniny("Rastislav, Čistomil, Čistoslav, Rastic, Rastimír, Ratislav, Vidor, Čistomila, Čistoslava, Rastislava, Ratislava", 13, 1)
	addMeniny("Radovan, Hilár, Uriáš, Uriel, Hilária, Radovana,", 14, 1)
	addMeniny("Dobroslav, Dobrotín, Domoslav, Loránt, Múdroslav, Domoslava,", 15, 1)
	addMeniny("Kristína", 16, 1)
	addMeniny("Nataša, Sofia,", 17, 1)
	addMeniny("Bohdana, Priskus, Piroška, Priska", 18, 1)
	addMeniny("Drahomíra, Mário, Sára, Márius, Dúbravka", 19, 1)
	addMeniny("Dalibor, Fabián, Fábius, Sebastián, Šebastián, Fábia, Fabiána, Fabiola, Sebastiána,", 20, 1)
	addMeniny("Vincent, Vincencia", 21, 1)
	addMeniny("Zora, Dorián, Sírius, Slavoľub, Slavomil, Zoran, Auróra, Cyntia, Doriána, Sinda, Slavomila, Zorana, Zara", 22, 1)
	addMeniny("Miloš, Miloň, Selma,", 23, 1)
	addMeniny("Timotej, Ctiboh, Timotea", 24, 1)
	addMeniny("Gejza, Saul, Šavol,", 25, 1)
	addMeniny("Tamara, Tamia, Polykarp, Slavibor, Slavislav, Slaviboj, Slavoboj, Svätoboj, Svätobor, Xenofón, Žarko, Polykarpa,", 26, 1)
	addMeniny("Bohuš, Pribislav, Pribiš,", 27, 1)
	addMeniny("Alfonz, Manfréd, Alfonzia,", 28, 1)
	addMeniny("Gašpar, Pribina", 29, 1)
	addMeniny("Ema, Jasna", 30, 1)
	addMeniny("Emil, Emilián, Emiliána, Marika", 31, 1)

	// Februar
	addMeniny("Tatiana, Hynek, Trifon, Táňa, Girron", 1, 2)
	addMeniny("Erik, Erika, Aida", 2, 2)
	addMeniny("Blažej, Celerín, Celerína", 3, 2)
	addMeniny("Veronika, Nika, Verena, Verona", 4, 2)
	addMeniny("Agáta, Moderát, Modest, Leda, Moderáta, Modesta", 5, 2)
	addMeniny("Dorota, Dorisa, Titanila", 6, 2)
	addMeniny("Vanda, Romuald", 7, 2)
	addMeniny("Zoja, Lejla, Aranka, Zoe", 8, 2)
	addMeniny("Zdenko, Rainold, Rinaldo, Zdeno, Apolena, Apoliena, Apolónia", 9, 2)
	addMeniny("Gabriela, Scholastika, Školastika", 10, 2)
	addMeniny("Dezider, Želislav, Dezidera, Želislava", 11, 2)
	addMeniny("Perla, Ron, Ronald, Zoro, Zoroslav, Eulália, Slavena, Solveiga, Zoroslava", 12, 2)
	addMeniny("Arpád, Jordán, Jordána", 13, 2)
	addMeniny("Valentín, Velimír", 14, 2)
	addMeniny("Pravoslav, Faust, Faustína, Georgia, Georgína, Pravoslava", 15, 2)
	addMeniny("Ida, Liana, Pamfil, Pamfília", 16, 2)
	addMeniny("Miloslava, Flavián, Flávius, Silván, Silvín, Flávia, Milomíra, Miluša, Silvána", 17, 2)
	addMeniny("Jaromír, Simeon, Jaromíra, Konkordia, Bernadetta", 18, 2)
	addMeniny("Vlasta, Konrád, Kurt", 19, 2)
	addMeniny("Lívia, Aladár, Lívio, Lívius, Udo, Ulrich, Alma, Ulrika, Ulriška, Aimee", 20, 2)
	addMeniny("Eleonóra", 21, 2)
	addMeniny("Etela, Etel", 22, 2)
	addMeniny("Roman, Romana, Romina", 23, 2)
	addMeniny("Matej, Jazmína, Goran, Mateja, Matias, Mateo, Matiáš, Yasmine, Jasmína", 24, 2)
	addMeniny("Frederik, Frederika, Taras, Federika", 25, 2)
	addMeniny("Viktor, Porfýr, Edina", 26, 2)
	addMeniny("Alexander, Leander, Sandro, Skender, Drahotína, Dražica, Leandra", 27, 2)
	addMeniny("Zlatica, Elemír, Elo, Lumír, Zlata", 28, 2)
	addMeniny("Radomír, Radomíra", 29, 2)

	// Marec
	addMeniny("Albín", 1, 3)
	addMeniny("Anežka", 2, 3)
	addMeniny("Bohumil, Bohumila, Ticián, Ginda, Kunigunda, Ticiána", 3, 3)
	addMeniny("Kazimír, Kevin, Gerazim, Romeo, Jadrana, Kazimíra", 4, 3)
	addMeniny("Fridrich, Lucius, Teofil, Friderika, Teofila", 5, 3)
	addMeniny("Radoslav, Radoslava, Fridolín, Koriolán, Radislav, Felícia, Fridolína, Radislava", 6, 3)
	addMeniny("Tomáš, Tomislav, Tomáška, Tomislava", 7, 3)
	addMeniny("Alan, Alana", 8, 3)
	addMeniny("Františka, Erhard", 9, 3)
	addMeniny("Branislav, Bruno, Bratislav, Bronislav, Bratislava, Taras", 10, 3)
	addMeniny("Angela, Angelika, Angel, Volfram, Algelína, Jurina", 11, 3)
	addMeniny("Gregor, Teofan, Gregora, Gregoria, Gregorína", 12, 3)
	addMeniny("Vlastimil, Kira, Rozína", 13, 3)
	addMeniny("Matilda, Metaneta", 14, 3)
	addMeniny("Svetlana, Agap, Belomír, Rodan, Roderich, Roderik, Torkvát, Agapa, Agapia, Rodana, Roderika", 15, 3)
	addMeniny("Boleslav, Amos, Bolemír, Heribert, Bolemíra", 16, 3)
	addMeniny("Ľubica, Ľuban, Ľuben, Zbignev, Zbyšek, Ľuba", 17, 3)
	addMeniny("Eduard, Ctislav, Salvátor, Ctislava, Eduarda", 18, 3)
	addMeniny("Jozef, Sibyla", 19, 3)
	addMeniny("Víťazoslav, Klaudián, Klaudín, Klaudio, Klaudius, Víťazoslava", 20, 3)
	addMeniny("Blahoslav, Blahoboj, Blahosej, Radek, Radko", 21, 3)
	addMeniny("Beňadik, Benedikt, Oktavián, Oktávius, Benedikta, Benilda, Benita, Izolda, Oktávia", 22, 3)
	addMeniny("Adrián, Apián, Dárius, Viktorián, Apia", 23, 3)
	addMeniny("Gabriel", 24, 3)
	addMeniny("Marián, Humbert, Anunciáta, Irida, Irisa", 25, 3)
	addMeniny("Emanuel, Eman, Manuel, Emanuela, Manuela", 26, 3)
	addMeniny("Alena, Rupert, Ruprecht, Dita, Leia", 27, 3)
	addMeniny("Soňa, Ilarion", 28, 3)
	addMeniny("Miroslav, Mieroslav, Bertold, Bertolda, Mieroslava", 29, 3)
	addMeniny("Vieroslava, Vieroľub, Vieromil, Vieroslav,", 30, 3)
	addMeniny("Benjamín, Kvído, Balbína", 31, 3)

	// Apríl
	addMeniny("Hugo, Hugolín", 1, 4)
	addMeniny("Zita, Áron", 2, 4)
	addMeniny("Richard, Richarda", 3, 4)
	addMeniny("Izidor, Izidora", 4, 4)
	addMeniny("Miroslava, Mira", 5, 4)
	addMeniny("Irena, Irína, Celestín, Ruben, Sixtus, Celestína, Venuša", 6, 4)
	addMeniny("Zoltán, Armand, Herman, Rufínus, Rúfus, Armanda, Rufína, Rumjana", 7, 4)
	addMeniny("Albert, Albertín, Albrecht, Valter, Alberta, Albertína, Albrechta", 8, 4)
	addMeniny("Milena, Erhard, Mileva", 9, 4)
	addMeniny("Igor, Ezechiel, Ivar, Ivor, Radomil, Igora, Radomila", 10, 4)
	addMeniny("Július, Antip, Ariel, Ariela, Arleta, Leo, Lev,", 11, 4)
	addMeniny("Estera, Aster, Davorín, Zenon, Astéria", 12, 4)
	addMeniny("Aleš, Artem, Artemon, Artemia, Artemida, Norma", 13, 4)
	addMeniny("Justína, Hrdoslav, Hrdoš, Justín, Davorína, Hrdoslava, Justa", 14, 4)
	addMeniny("Fedor, Fedora", 15, 4)
	addMeniny("Dana, Danica", 16, 4)
	addMeniny("Rudolf, Ralf, Rolf, Rudolfa, Rudolfína, Rudko", 17, 4)
	addMeniny("Valér, Apolón, Erich, Verner, Ilma", 18, 4)
	addMeniny("Jela, Krescenc, Krescencia", 19, 4)
	addMeniny("Marcel, Hvezdoň", 20, 4)
	addMeniny("Ervín, Abelard, Adelard, Anzelm, Žitoslav, Anzelma, Ervína, Saskia, Žitoslava, Elissa", 21, 4)
	addMeniny("Slavomír, Slávo, Tvrdomír, Jelena, Noema", 22, 4)
	addMeniny("Vojtech, Adalbert, Roger, Adalberta, Vojtecha, Vojteška", 23, 4)
	addMeniny("Juraj, Fidél, Gaston, Georg, Helmut, Jorik, Jürgen, Deora, Fidélia, Jorga, Jorika, Juraja", 24, 4)
	addMeniny("Marek, Izmael, Marko, Markus, Marco", 25, 4)
	addMeniny("Jaroslava", 26, 4)
	addMeniny("Jaroslav, Aristid, Tulius, Aristída, Tulia", 27, 4)
	addMeniny("Jarmila, Prudencius, Prudencia", 28, 4)
	addMeniny("Lea, Timon", 29, 4)
	addMeniny("Anastázia, Anastáz, Blahomil, Asia, Blahomila, Nasťa, Nastasia", 30, 4)

	//Máj
	addMeniny("Amarila, Pamela", 1, 5)
	addMeniny("Žigmund, Atanáz, Atanázia, Aténa", 2, 5)
	addMeniny("Galina, Timea, Horác, Desana, Halina", 3, 5)
	addMeniny("Florián, Flór, Aglája, Floriána, Florína, Pelagia", 4, 5)
	addMeniny("Lesana, Gothard, Pius, Lesia, Pia, Toska", 5, 5)
	addMeniny("Hermína, Ovídius, Radivoj, Tankréd, Elfrída, Frída, Herina, Mineta", 6, 5)
	addMeniny("Monika, Napoleon, Stanimír, Mona", 7, 5)
	addMeniny("Ingrida, Ina, Inga", 8, 5)
	addMeniny("Roland, Rolanda, Christopher", 9, 5)
	addMeniny("Viktória, Armín, Armína, Beatrica", 10, 5)
	addMeniny("Blažena, Miranda, Svatava", 11, 5)
	addMeniny("Pankrác, Achiles", 12, 5)
	addMeniny("Servác, Chraniboj, Chranibor, Chranislav, Servián, Chranislava, Imelda, Konzuela", 13, 5)
	addMeniny("Bonifác", 14, 5)
	addMeniny("Žofia, Brenda, Raisa, Sofia, Zosia, Sophia, Sophie", 15, 5)
	addMeniny("Svetozár, Peregrín, Peregrína", 16, 5)
	addMeniny("Gizela, Andronik, Ditmar, Paskal, Andronika, Paskália", 17, 5)
	addMeniny("Viola", 18, 5)
	addMeniny("Gertrúda, Gerda", 19, 5)
	addMeniny("Bernard, Bernardín, Hviezdoslav, Bernadeta, Bernarda, Bernardína, Hviezdoslava", 20, 5)
	addMeniny("Zina, Dobromír, Hostimil, Hostirad, Hostislav, Hostisvit, Teobald, Dobromíra, Hostimila, Hostislava", 21, 5)
	addMeniny("Júlia, Juliana, Liana, Rita", 22, 5)
	addMeniny("Želmíra, Želmír, Želimír", 23, 5)
	addMeniny("Ela, Elora", 24, 5)
	addMeniny("Urban, Vanesa", 25, 5)
	addMeniny("Dušan", 26, 5)
	addMeniny("Iveta, Vadim, Valdemar, Valdemara", 27, 5)
	addMeniny("Viliam, Vilhelm, Elektra, Elma, Vilhelmína, William", 28, 5)
	addMeniny("Vilma, Elmar, Maxim, Maxima", 29, 5)
	addMeniny("Ferdinand, Neander, Ferdinanda", 30, 5)
	addMeniny("Petrana, Petronela, Petrónius, Blahoslav, Nela, Petrónia, Nelly", 31, 5)

	//Jún
	addMeniny("Žaneta", 1, 6)
	addMeniny("Oxana, Xénia, Karmen, Karmena, Erazim, Erazmus, Jaromil, Vlastimila", 2, 6)
	addMeniny("Karolína, Kevin, Lino, Linus, Palmíro, Kaja, Klotilda, Lina, Lineta, Palmíra", 3, 6)
	addMeniny("Lenka, Lena", 4, 6)
	addMeniny("Laura, Dorotej, Fatima, Laurencia, Loreta, Loriána", 5, 6)
	addMeniny("Norbert, Norman, Romulus, Norberta, Perzida", 6, 6)
	addMeniny("Róbert, Borislav, Robin, Teodot, Dalma, Oriána, Róberta, Robina, Silver", 7, 6)
	addMeniny("Medard", 8, 6)
	addMeniny("Stanislava, Felicián, Prímus, Vojeslav, Berenika, Vojeslava", 9, 6)
	addMeniny("Margaréta, Gréta", 10, 6)
	addMeniny("Dobroslava, Barnabáš, Dobrava, Dobrota, Dobrotína, Flóra, Pavoslava", 11, 6)
	addMeniny("Zlatko, Svätoslav, Svetislav, Svetoslav, Zlatan, Zlatomír, Zlatoň, Zlatoš, Svätoslava, Svetislava, Svetoslava, Zlatana, Zlatomíra", 12, 6)
	addMeniny("Anton, Genadij, Tobiáš, Tobias", 13, 6)
	addMeniny("Vasil, Bazil, Elizej, Kvintilián, Kvintín, Kvintus, Herta, Kvinta, Kvintiliána, Quentin", 14, 6)
	addMeniny("Vít, Jolana", 15, 6)
	addMeniny("Bianka, Blanka, Benon, Božetech, Alina, Božetecha", 16, 6)
	addMeniny("Adolf, Adolfína", 17, 6)
	addMeniny("Vratislav, Leontín, Milovan, Milovín, Sedrik, Leontína, Milovana", 18, 6)
	addMeniny("Alfréd, Leonid, Leonídas, Leoš, Ruslan, Alfréda", 19, 6)
	addMeniny("Valéria, Florencián, Florentín, Silver, Florencia, Florentína", 20, 6)
	addMeniny("Alojz, Elvis, Lejla", 21, 6)
	addMeniny("Paulína, Achác, Eberhard, Paulín, Paula, Rozvita, Zaira", 22, 6)
	addMeniny("Sidónia, Sidón", 23, 6)
	addMeniny("Ján, Janis, Jaško, Jens, Johan, Jovan, Nino, Sean", 24, 6)
	addMeniny("Tadeáš, Olívia, Olívius, Prosper, Febrónia, Oliva", 25, 6)
	addMeniny("Adriána, Stojan, Adriena, Ria, Riana, Stojana", 26, 6)
	addMeniny("Ladislav, Ladislava, Samson, Sulamita", 27, 6)
	addMeniny("Beáta, Beátus, Slavoj, Bea", 28, 6)
	addMeniny("Peter, Pavol, Petra, Pavel, Pavla, Petula", 29, 6)
	addMeniny("Melánia, Vlastibor, Vlastimír, Šárka, Vlastimíra", 30, 6)
	// Júl
	addMeniny("Diana, Dean, Dejan, Dina, Zian, Dajana, Deana, Kalina, Tabita", 1, 7)
	addMeniny("Berta, Bertín, Bertína", 2, 7)
	addMeniny("Miloslav, Irenej, Miliduch, Milomír, Milorad, Radimír, Rodimír, Radimíra", 3, 7)
	addMeniny("Prokop, Procius, Prokopa", 4, 7)
	addMeniny("Cyril, Metod, Cyrus, Cyrila", 5, 7)
	addMeniny("Patrik, Patrícia, Patrokles", 6, 7)
	addMeniny("Oliver, Donald, Kastor, Veleslav, Velislav, Valibals, Veleslava, Velislava", 7, 7)
	addMeniny("Ivan, Ivo, Kilián, Perikles", 8, 7)
	addMeniny("Lujza, Lukrécius, Lizelota, Lukrécia", 9, 7)
	addMeniny("Amália, Amína, Lada", 10, 7)
	addMeniny("Milota, Milutín", 11, 7)
	addMeniny("Nina, Fortunát, Fortunáta", 12, 7)
	addMeniny("Margita, Arne, Borivoj, Merkéta,", 13, 7)
	addMeniny("Kamil", 14, 7)
	addMeniny("Henrich, Egon, Enrik, Enriko, Henrik, Henrika, Lota, Šarlota", 15, 7)
	addMeniny("Drahomír, Karmela, Rút, Rúta", 16, 7)
	addMeniny("Bohuslav, Božislav, Svorad", 17, 7)
	addMeniny("Kamila, Rowa", 18, 7)
	addMeniny("Dušana", 19, 7)
	addMeniny("Eliáš, Iľja, Ilia, Eliána, Iliana, Elisa", 20, 7)
	addMeniny("Daniel, Dan, Dalina", 21, 7)
	addMeniny("Magdaléna, Magda, Mahuliena, Majda", 22, 7)
	addMeniny("Oľga, Apolinár, Libérius, Libor, Liborius, Apolinára, Libora, Lilien", 23, 7)
	addMeniny("Vladimír, Kinga", 24, 7)
	addMeniny("Jakub, Žakelína", 25, 7)
	addMeniny("Anna, Hana, Aneta, Anica, Anita, Annamária, Naneta, Joachim", 26, 7)
	addMeniny("Božena, Gorazd, Pantaleon", 27, 7)
	addMeniny("Krištof, Inocent, Svätomír, Svätoš, Inocencia, Nausika, Svätomíra", 28, 7)
	addMeniny("Marta, Olaf, Serafín, Serafa, Serafína", 29, 7)
	addMeniny("Libuša, Abdon, Ingemar, Ingeborga, Ľubuša, Rowena", 30, 7)
	addMeniny("Ignác, Ignát, Vatroslav, Ignácia", 31, 7)

	// August
	addMeniny("Božidara, Božidar, Ľudomír, Božica, Kleopatra, Ľudomíra, Penelopa", 1, 8)
	addMeniny("Gustáv, Gustáva", 2, 8)
	addMeniny("Jerguš, Nikodém, Nikodéma", 3, 8)
	addMeniny("Dominik, Dominika, Krasoslav, Rainer, Krasoslava, Donna", 4, 8)
	addMeniny("Hortenzia, Hortenz, Milivoj, Osvald, Snežana", 5, 8)
	addMeniny("Jozefína, Nehoslav, Jozefa", 6, 8)
	addMeniny("Štefánia, Kajetán, Afra, Afrodita, Kajetána, Štefana", 7, 8)
	addMeniny("Oskár, Donát, Hartvig, Virgín, Donáta, Virgínia", 8, 8)
	addMeniny("Ľubomíra, Rastic", 9, 8)
	addMeniny("Vavrinec, Lars, Laurenc, Laurus, Lorenc, Vavro", 10, 8)
	addMeniny("Zuzana, Trojan, Dulcia, Dulcinela, Dulcínia", 11, 8)
	addMeniny("Darina, Dárius, Dária", 12, 8)
	addMeniny("Ľubomír, Hypolit, Kasián, Kasius, Belinda", 13, 8)
	addMeniny("Mojmír, Eusébius, Mojtech, Eusébia", 14, 8)
	addMeniny("Marcela", 15, 8)
	addMeniny("Leonard, Jáchim, Joachim, Linhart, Rochus, Leonarda", 16, 8)
	addMeniny("Milica, Bertram, Bertrand, Hyacint, Libert, Miron, Hyacinta", 17, 8)
	addMeniny("Elena, Helena, Ilona", 18, 8)
	addMeniny("Lýdia, Vratislava, Lilien", 19, 8)
	addMeniny("Anabela, Arabela, Liliana", 20, 8)
	addMeniny("Jana, Janka, Johana, Jovana", 21, 8)
	addMeniny("Tichomír, Sigfríd, Tichomil, Tichomíra", 22, 8)
	addMeniny("Filip, Vlastislav, Filipa, Filipína, Vlastislava", 23, 8)
	addMeniny("Bartolomej, Bartolomea", 24, 8)
	addMeniny("Ľudovít, Ludvig, Radim, Ľudovíta", 25, 8)
	addMeniny("Samuel, Samo, Zemfír, Samuela, Tália, Zemfíra", 26, 8)
	addMeniny("Silvia, Silvio, Silvius", 27, 8)
	addMeniny("Augustín, August, Augusta, Augustína, Gustína", 28, 8)
	addMeniny("Nikola, Nikolaj, Koleta, Nikoleta,Nikolas", 29, 8)
	addMeniny("Ružena, Ružica", 30, 8)
	addMeniny("Nora, Rajmund, Ramón, Rajmunda, Ramona", 31, 8)
	// September
	addMeniny("Drahoslava, Egid, Egídius, Deborah", 1, 9)
	addMeniny("Linda, Absolón, Axel, Justus, Ermelinda, Melinda, Rebeka", 2, 9)
	addMeniny("Belo, Antim, Klélia", 3, 9)
	addMeniny("Rozália, Kandid, Mojžiš, Rozalín, Rozálio, Kandida, Róza, Rozeta, Rozita, Rusalka", 4, 9)
	addMeniny("Regína, Bojan, Bojimír, Bojislav, Borimír, Branimír, Chotimír, Justinián, Otakar, Regan, Regulus, Viktorín, Bojana, Bojimíra, Boislava, Branimíra, Budislava, Chotimíra, Larisa", 5, 9)
	addMeniny("Alica, Brian, Magnus, Mansvét, Zachariáš, Bria, Larisa", 6, 9)
	addMeniny("Marianna, Mariana", 7, 9)
	addMeniny("Miriama, Miriana", 8, 9)
	addMeniny("Martina, Gordan, Gordián, Gordon, Omar, Gordana, Rea, Tina", 9, 9)
	addMeniny("Oleg, Honór, Vitold, Honóra, Krasava, Vitolda", 10, 9)
	addMeniny("Bystrík, Prótus, Zdislav, Helga, Zdislava", 11, 9)
	addMeniny("Mária, Maja, Manon, Manona, Marica, Mariela, Marieta, Marika, Marila, Mariola, Marlena, Marusia, Jessica, Mia", 12, 9)
	addMeniny("Ctibor, Amát, Amátus, Stibor, Sven, Amáta, Tobias", 13, 9)
	addMeniny("Ľudomil, Dragan, Dragutín, Drahan, Drahotín, Ľudomila, Radka, Serena", 14, 9)
	addMeniny("Jolana, Melissa, Melisa, Melita", 15, 9)
	addMeniny("Ľudmila, Dunja", 16, 9)
	addMeniny("Olympia, Lambert, Záviš", 17, 9)
	addMeniny("Eugénia, Ariadna", 18, 9)
	addMeniny("Konštantín, Trofín, Konstancia, Konštantína", 19, 9)
	addMeniny("Ľuboslav, Ľuboslava, Eustach, Filibert, Liboslav, Eustachia, Liboslava", 20, 9)
	addMeniny("Matúš, Ifigénia, Mirela", 21, 9)
	addMeniny("Móric, Maurícius, Maurus", 22, 9)
	addMeniny("Zdenka, Polyxénia, Tekla, Zdena", 23, 9)
	addMeniny("Ľubor, Ľuboš, Terenc", 24, 9)
	addMeniny("Vladislav, Vladivoj, Eufrozina, Fruzína, Vladislava, Jesika", 25, 9)
	addMeniny("Edita, Damián, Kozmas, Damiána,", 26, 9)
	addMeniny("Cyprián, Mirabela", 27, 9)
	addMeniny("Václav, Chariton, Kariton, Václava", 28, 9)
	addMeniny("Michal, Michaela, Michael, Michala", 29, 9)
	addMeniny("Jarolím, Hieronym, Jeremiáš, Jarolíma, Ráchel, Ráchela, Una", 30, 9)

	// Október
	addMeniny("Arnold, Remig, Remus, Arnolda, Belina", 1, 10)
	addMeniny("Levoslav, Leodegar, Levoslava", 2, 10)
	addMeniny("Stela, Amadeus, Evald, Amadea", 3, 10)
	addMeniny("František, Edvin, Fraňo", 4, 10)
	addMeniny("Viera, Blahomír, Placid, Blahomíra, Karitína, Placida", 5, 10)
	addMeniny("Natália", 6, 10)
	addMeniny("Eliška", 7, 10)
	addMeniny("Brigita, Brit, Brita", 8, 10)
	addMeniny("Dionýz, Dionýzia", 9, 10)
	addMeniny("Slavomíra, Gedeon, Záboj, Krasomila", 10, 10)
	addMeniny("Valentína, Belín, Zvonimír, Zvonislav, Bruna, Brunhilda, Luneta, Selena, Zvonimíra, Zvonislava", 11, 10)
	addMeniny("Maximilián, Max, Maximiliána", 12, 10)
	addMeniny("Koloman, Edgar", 13, 10)
	addMeniny("Boris, Borislav, Kalist, Borislava, Kalista", 14, 10)
	addMeniny("Terézia, Tereza", 15, 10)
	addMeniny("Vladimíra, Gál, Havel, Havla", 16, 10)
	addMeniny("Hedviga, Jadviga", 17, 10)
	addMeniny("Lukáš", 18, 10)
	addMeniny("Kristián, Christián, Izák, Christiána, Kristiána", 19, 10)
	addMeniny("Vendelín, Eunika, Vendelína", 20, 10)
	addMeniny("Uršuľa, Anatol, Anatólia, Antília", 21, 10)
	addMeniny("Sergej, Dobromil, Sergius, Zdravomil, Kordula, Korduľa, Pribislava, Saloma, Saloména, Solomia", 22, 10)
	addMeniny("Alojzia, Žitomír", 23, 10)
	addMeniny("Kvetoslava, Aretas, Cvetan, Gilbert, Harold, Herald, Krasomil, Kvetoň, Kvetoslav, Rafael, Šalamún, Areta, Cvetana, Gilberta, Kveta, Kvetana, Kvetava, Rafaela", 24, 10)
	addMeniny("Aurel, Krišpín, Vojmír, Zosim, Živan, Živko, Dália, Vojmíra, Živa, Živana", 25, 10)
	addMeniny("Demeter, Amand, Dimitrij, Evarist, Amanda, Demetria", 26, 10)
	addMeniny("Sabína, Horislav, Hromislav, Horislava, Hromislava, Sabrina, Zoa, Zoana", 27, 10)
	addMeniny("Dobromila, Kevin", 28, 10)
	addMeniny("Klára, Narcis, Zenob, Klarisa, Narcisa, Zenóbia, Chiara", 29, 10)
	addMeniny("Šimon, Simona, Arzen, Asen, Simon, Asena, Simoneta, Šimona", 30, 10)
	addMeniny("Aurélia, Stacho, Volfgang", 31, 10)

	// November
	addMeniny("Denis, Denisa", 1, 11)
	addMeniny(" Cézar, Cezária", 2, 11)
	addMeniny("Hubert", 3, 11)
	addMeniny("Karol, Džesika, Jesika, Karola, Skarleta, Jessica, Yessica", 4, 11)
	addMeniny("Imrich, Emerich, Imriška", 5, 11)
	addMeniny("Renáta, Renát, Renáto, Renátus", 6, 11)
	addMeniny("René, Engelbert", 7, 11)
	addMeniny("Bohumír, Bohumíra", 8, 11)
	addMeniny("Teodor, Orest, Teo, Teodorik, Teodoz, Deodata, Tea, Teodora, Teodózia", 9, 11)
	addMeniny("Tibor, Tiber, Meluzína, Tibora, Tobias", 10, 11)
	addMeniny("Maroš, Martin, Martinián", 11, 11)
	addMeniny("Svätopluk, Astrid, Jonáš, Astrida", 12, 11)
	addMeniny("Stanislav, Orin", 13, 11)
	addMeniny("Irma, Juventín, Mladen, Mladoň, Mladotín, Ima, Juventína, Mladena, Mladotína", 14, 11)
	addMeniny("Leopold, Leopolda, Leopoldína", 15, 11)
	addMeniny("Agnesa, Otmar, Agneša, Inéza", 16, 11)
	addMeniny("Klaudia, Klodeta", 17, 11)
	addMeniny("Eugen, Platón", 18, 11)
	addMeniny("Alžbeta, Betina, Elizabeta, Lila, Liliana, Líza, Lili, Lilly, Lily", 19, 11)
	addMeniny("Félix, Filemon, Homér", 20, 11)
	addMeniny("Elvíra, Ctirad, Ctirada", 21, 11)
	addMeniny("Cecília, Cecilián, Šejla", 22, 11)
	addMeniny("Klement, Klementín, Kliment, Kolumbín, Klementína, Kolumbína", 23, 11)
	addMeniny("Emília, Milín, Milina", 24, 11)
	addMeniny("Katarína, Katrina", 25, 11)
	addMeniny("Kornel, Valerián", 26, 11)
	addMeniny("Milan, Nestor, Virgil, Milana", 27, 11)
	addMeniny("Henrieta, Gerhard, Tristan, Desdemona, Eta", 28, 11)
	addMeniny("Vratko, Saturnín, Zaida", 29, 11)
	addMeniny("Andrej, Ondrej, Andreas", 30, 11)
	// December
	addMeniny("Edmund, Edmunda", 1, 12)
	addMeniny("Bibiána, Budimír, Budislav, Budimíra, Vivien", 2, 12)
	addMeniny("Oldrich, Sofron, Xavér, Sofrónia, Xavéria", 3, 12)
	addMeniny("Barbora, Babeta, Barbara, Barica", 4, 12)
	addMeniny("Oto, Gerald, Otakar, Otokar, Geralda, Geraldína, Jitka, Ota, Sáva", 5, 12)
	addMeniny("Mikuláš, Nikita, Niko, Nikolas, Mikuláška, Nikoleta", 6, 12)
	addMeniny("Ambróz, Amarant, Amaranta, Ambrózia", 7, 12)
	addMeniny("Marína", 8, 12)
	addMeniny("Izabela, Dalila, Leokádia", 9, 12)
	addMeniny("Radúz, Herbert", 10, 12)
	addMeniny("Hilda, Hildegard, Hildegarda", 11, 12)
	addMeniny("Otília, Spiridon, Dília, Odeta", 12, 12)
	addMeniny("Lucia, Rosan, Rosana, Roxana", 13, 12)
	addMeniny("Branislava, Bronislava, Broňa", 14, 12)
	addMeniny("Ivica, Detrich, Radan, Radana", 15, 12)
	addMeniny("Albína, Bela, Teofánia", 16, 12)
	addMeniny("Kornélia, Lazár, Kora, Korina", 17, 12)
	addMeniny("Sláva, Slávka, Gracián, Grácia, Graciána, Slavislava", 18, 12)
	addMeniny("Judita, Abrahám, Mstislav, Neméz, Ita, Mstislava, Neméza", 19, 12)
	addMeniny("Dagmara, Dagmar, Dag, Dagobert, Daga, Damara", 20, 12)
	addMeniny("Bohdan", 21, 12)
	addMeniny("Adela, Ada, Adelaida, Adelgunda, Adelína, Adina, Alida", 22, 12)
	addMeniny("Nadežda, Naďa", 23, 12)
	addMeniny("Adam, Eva, Evamária, Evelína, Gaja, Gajana, Geja", 24, 12)
	addMeniny("", 25, 12)
	addMeniny("Štefan", 26, 12)
	addMeniny("Filoména, Filomén", 27, 12)
	addMeniny("Ivana, Ivona, Iva", 28, 12)
	addMeniny("Milada, Jonatán, Miladín, Nátan, Natanel", 29, 12)
	addMeniny("Dávid, Lotar", 30, 12)
	addMeniny("Silvester, Horst", 31, 12)
}

//Created by Richard Malaschitz
//2018-12-27 17:07
//Copyright (c) 2018. All Rights Reserved.
